import * as T from './vendor/three.module.js';
import {OrbitControls} from './vendor/addons/controls/OrbitControls.js';
import {EffectComposer} from './vendor/addons/postprocessing/EffectComposer.js';
import {RenderPass} from './vendor/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from './vendor/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from './vendor/addons/postprocessing/OutputPass.js';
import {RoomEnvironment} from './vendor/addons/environments/RoomEnvironment.js';
import {buildProfessor} from './professor-scene.js';
import {buildWorld} from './world.js';

const host=document.getElementById('world-layer');
let professor=null,introActive=false,introStep=0,renderPass,world,renderer,composer,bloom,controls,camera,resizeObserver,raf=0,active=true,paused=false,autoOrbit=false,night=0,targetNight=0,frameTime=0,last=0,elapsed=0,slowFrames=0,currentState=null,tween=null,quality='balanced',pinCache=[],lastPinRefresh=0;
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const mobile=window.matchMedia('(max-width:760px)').matches;
const orientation=new T.Vector3(),projected=new T.Vector3();
function announce(text){const status=document.getElementById('scene-status');if(status)status.textContent=text;}
function fail(message){cancelAnimationFrame(raf);host.classList.add('scene-failed');host.innerHTML='<div class="scene-fallback"><p>'+message+'</p><button type="button" id="retry-3d">Retry 3D</button></div>';document.getElementById('retry-3d').onclick=()=>location.reload();document.body.classList.add('world-failed');}
function overview(){const aspect=host.clientWidth/Math.max(1,host.clientHeight);const factor=aspect<.8?1.42:aspect<1.1?1.15:1;return {target:new T.Vector3(0,3,0),position:new T.Vector3(55*factor,43*factor,66*factor)};}
function flyTo(target,position){tween={start:performance.now(),duration:reduced?1:1300,from:camera.position.clone(),to:position.clone(),fromTarget:controls.target.clone(),toTarget:target.clone()};autoOrbit=false;syncControls();}
function syncControls(){document.querySelectorAll('[data-camera="orbit"]').forEach(b=>{b.classList.toggle('active',autoOrbit);b.setAttribute('aria-pressed',String(autoOrbit));});document.querySelectorAll('[data-camera="night"]').forEach(b=>{b.classList.toggle('active',targetNight>0);b.setAttribute('aria-pressed',String(targetNight>0));});document.querySelectorAll('[data-camera="quality"]').forEach(b=>{b.textContent=quality==='high'?'Ultra':quality==='balanced'?'Balanced':'Battery';b.setAttribute('aria-label','Graphics quality: '+b.textContent);});}
function qualitySettings(){const cap=quality==='high'?1.8:quality==='balanced'?(mobile?1.25:1.5):.85;renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,cap));renderer.shadowMap.enabled=quality!=='battery';world.sun.shadow.mapSize.set(quality==='high'?2048:1024,quality==='high'?2048:1024);if(world.sun.shadow.map){world.sun.shadow.map.dispose();world.sun.shadow.map=null;}bloom.enabled=quality!=='battery';resize();syncControls();}
function resize(){if(!renderer)return;const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);composer.setSize(w,h);}
function render(now){raf=requestAnimationFrame(render);if(!active||paused||document.hidden){last=now;return;}const dt=Math.min(.05,(now-(last||now))/1000);last=now;elapsed+=dt;if(introActive){professor??=buildProfessor();professor.scene.environment=world.scene.environment;professor.scene.environmentIntensity=.3;controls.enabled=false;professor.update(reduced?0:elapsed,introStep,host.clientWidth/host.clientHeight);renderPass.scene=professor.scene;renderPass.camera=professor.camera;renderer.toneMappingExposure=1.12;bloom.strength=.12;composer.render();return;}controls.enabled=true;renderPass.scene=world.scene;renderPass.camera=camera;night=T.MathUtils.damp(night,targetNight,2,dt);if(tween){const p=Math.min(1,(now-tween.start)/tween.duration),k=p<.5?4*p*p*p:1-Math.pow(-2*p+2,3)/2;camera.position.lerpVectors(tween.from,tween.to,k);controls.target.lerpVectors(tween.fromTarget,tween.toTarget,k);if(p===1)tween=null;}controls.autoRotate=autoOrbit&&!tween&&!reduced;controls.update(dt);world.update(reduced?0:elapsed,night,currentState);renderer.toneMappingExposure=T.MathUtils.lerp(1.05,1.22,night);bloom.strength=T.MathUtils.lerp(.32,.6,night);composer.render();
 if(now-lastPinRefresh>300){pinCache=[...document.querySelectorAll('[data-world-pin]')];lastPinRefresh=now;}
 const width=host.clientWidth,height=host.clientHeight;for(const pin of pinCache){const point=world.hotspots.find(p=>p.id===pin.dataset.worldPin);if(!point)continue;projected.copy(point.position).project(camera);const x=(projected.x*.5+.5)*width,y=(-projected.y*.5+.5)*height;const inside=projected.z<1&&projected.z> -1&&x>25&&x<width-25&&y>140&&y<height-140;pin.style.transform=`translate3d(${x}px,${y}px,0)`;pin.style.visibility=inside?'visible':'hidden';}
 if(now%5<1){camera.getWorldDirection(orientation);const angle=Math.atan2(orientation.x,orientation.z);document.querySelector('.compass-needle')?.style.setProperty('transform',`rotate(${-angle}rad)`);}
 // Lower the resolution only after sustained slow frames; never repeatedly recreate the renderer.
 frameTime=frameTime*.97+dt*1000*.03;if(frameTime>38&&quality==='balanced')slowFrames++;else slowFrames=Math.max(0,slowFrames-1);if(slowFrames>150){quality='battery';qualitySettings();announce('Battery graphics enabled for smoother motion');slowFrames=0;}
}
function initialize(){try{renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.domElement.setAttribute('aria-label','Interactive 3D laboratory campus. Drag to orbit; pinch or scroll to zoom.');renderer.domElement.tabIndex=0;host.appendChild(renderer.domElement);world=buildWorld();camera=new T.PerspectiveCamera(44,1,.3,1400);const start=overview();camera.position.copy(start.position);controls=new OrbitControls(camera,renderer.domElement);controls.target.copy(start.target);controls.enableDamping=true;controls.dampingFactor=.065;controls.enablePan=true;controls.panSpeed=.7;controls.rotateSpeed=.55;controls.zoomSpeed=.75;controls.minDistance=14;controls.maxDistance=190;controls.minPolarAngle=.2;controls.maxPolarAngle=Math.PI*.475;controls.autoRotateSpeed=.3;controls.maxTargetRadius=45;controls.addEventListener('start',()=>{tween=null;autoOrbit=false;syncControls();});
 const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),environment=pmrem.fromScene(room,.04);world.scene.environment=environment.texture;world.scene.environmentIntensity=.55;room.dispose();pmrem.dispose();
 composer=new EffectComposer(renderer);renderPass=new RenderPass(world.scene,camera);composer.addPass(renderPass);bloom=new UnrealBloomPass(new T.Vector2(host.clientWidth,host.clientHeight),.32,.6,1.1);composer.addPass(bloom);composer.addPass(new OutputPass());qualitySettings();controls.update();world.update(0,0,currentState);if(window.__labSnapshot?.intro){introActive=true;introStep=window.__labSnapshot.introStep||0;professor=buildProfessor();professor.scene.environment=environment.texture;professor.update(0,introStep,host.clientWidth/host.clientHeight);renderPass.scene=professor.scene;renderPass.camera=professor.camera;}composer.render();host.classList.add('ready');document.body.classList.add('world-ready');announce('Drag to orbit · Pinch to explore');resizeObserver=new ResizeObserver(resize);resizeObserver.observe(host);renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();paused=true;announce('3D paused. Restoring graphics…');});renderer.domElement.addEventListener('webglcontextrestored',()=>{paused=false;announce('Graphics restored');});
 renderer.domElement.addEventListener('keydown',e=>{if(e.key==='Home'){const v=overview();flyTo(v.target,v.position);}else if(e.key==='+'||e.key==='='){camera.position.lerp(controls.target,.12);}else if(e.key==='-'){camera.position.sub(controls.target).multiplyScalar(1.12).add(controls.target);}else return;e.preventDefault();});
 document.addEventListener('click',e=>{const b=e.target.closest('[data-camera]');if(!b)return;switch(b.dataset.camera){case'reset':{const v=overview();flyTo(v.target,v.position);break;}case'orbit':autoOrbit=!autoOrbit;break;case'night':targetNight=targetNight?0:1;break;case'quality':quality=quality==='balanced'?'high':quality==='high'?'battery':'balanced';qualitySettings();break;case'cinema':document.body.classList.toggle('cinematic');requestAnimationFrame(resize);break;case'zoom-in':camera.position.lerp(controls.target,.18);break;case'zoom-out':camera.position.sub(controls.target).multiplyScalar(1.18).add(controls.target);break;}syncControls();});
 raf=requestAnimationFrame(render);
 }catch(error){console.error('Campus 3D initialization failed:',error);fail('The 3D campus could not start on this device. The management screens are still available.');}}
window.addEventListener('lab-render',e=>{currentState=e.detail.state;introActive=!!e.detail.intro;introStep=e.detail.introStep||0;active=introActive||e.detail.tab==='campus';host.classList.toggle('scene-hidden',!active);document.body.classList.toggle('campus-view',active);if(active){lastPinRefresh=0;syncControls();if(renderer)announce('Drag to orbit · Pinch to explore');}});
window.addEventListener('lab-camera',e=>{if(!world)return;const spot=world.hotspots.find(p=>p.id===e.detail);if(spot)flyTo(spot.target,spot.camera);});
window.addEventListener('pagehide',()=>{paused=true;});window.addEventListener('pageshow',()=>{paused=false;});
initialize();
