import {branches,techs,roles,buildings,policies,economy,available,playerProgress,events} from './engine.js';
import {modelBranches,modelTechs,modelMeters,modelSources} from './model-tech.js';
import {ensureModel,canDevelop,modelReach,rivalModelProfiles} from './model-system.js';
import {modelGauges,vitrine} from './model-ui.js';

export const ui={section:{people:'team',world:'race',council:'policies',model:'home'},index:{},research:'architecture',modelBranch:'reason',researchPicker:false,modelPicker:false,info:false};
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cash=n=>(n<0?'−':'')+'$'+Math.abs(n).toFixed(Math.abs(n)<10?1:0)+'M';
const date=m=>new Date(Date.UTC(2023,m,1)).toLocaleDateString('en-US',{month:'short',year:'numeric',timeZone:'UTC'});
const btn=(act,id,label,disabled=false,cls='')=>`<button class="${cls}" ${cls==='hh-back'?`aria-label="${act==='tab'?'Back to campus':act==='close'?'Close menu':'Back to menu'}"`:''} data-act="${act}" data-id="${id}" ${disabled?'disabled':''}>${label}</button>`;
const control=(act,id,label,disabled=false,extra='')=>`<button data-ui="${act}" data-id="${id}" ${disabled?'disabled':''} ${extra}>${label}</button>`;
const labels={cap:'capability',rp:'RP / month',revenue:'$M revenue / month',trust:'trust',gov:'relations',safety:'safety',welfare:'welfare',climate:'environment',equality:'prosperity',risk:'exposure',...Object.fromEntries(Object.entries(modelMeters).map(([k,v])=>[k,v[0]]))};
const effects=e=>Object.entries(e).map(([k,v])=>`${v>0?'+':''}${v} ${labels[k]||k}`).join(' · ');
const meter=(v)=>`<div class="bar"><i style="width:${Math.min(100,Math.max(0,v))}%"></i></div>`;
function index(key,n){return Math.min(Math.max(0,ui.index[key]||0),Math.max(0,n-1));}
function pager(key,n,label=''){const i=index(key,n);return `<nav class="hh-pager" aria-label="${esc(label||'Item pages')}">${control('page',key+':'+(i-1),'←',i===0,'aria-label="Previous item"')}<span aria-live="polite">${esc(label)} <b>${n?i+1:0} / ${n}</b></span>${control('page',key+':'+(i+1),'→',i>=n-1,'aria-label="Next item"')}</nav>`;}
function tabs(area,items){return `<nav class="hh-tabs" aria-label="${area} sections">${items.map(([id,label])=>control('section',area+':'+id,label,false,`aria-pressed="${ui.section[area]===id}"`)).join('')}</nav>`;}
function screen(title,kicker,body,footer='',back=''){return `<section class="hh-screen"><header class="hh-heading">${back||btn('tab','campus','‹','', 'hh-back')}<div><span class="eyebrow">${kicker}</span><h1 tabindex="-1">${title}</h1></div></header><div class="hh-body">${body}</div>${footer}</section>`;}
function card(kicker,title,content,foot='',symbol=''){return `<article class="hh-card">${symbol?`<div class="hh-symbol" aria-hidden="true">${symbol}</div>`:''}<span class="eyebrow">${kicker}</span><h2>${esc(title)}</h2><div class="hh-copy">${content}</div>${foot?`<div class="hh-card-action">${foot}</div>`:''}</article>`;}
function branchPicker(model=false){const list=model?modelBranches:branches;return `<div class="hh-picker">${list.map(([id,name,icon])=>control(model?'model-branch':'research-branch',id,`<b>${icon}</b><span>${name}</span>`)).join('')}</div>`;}
function tierRail(list,key,done){return `<nav class="hh-tiers" aria-label="Technology tiers">${list.map((t,i)=>control('page',key+':'+i,`${done.includes(t.id)?'✓':t.tier}`,false,`aria-label="Tier ${t.tier}: ${esc(t.name)}" aria-pressed="${index(key,list.length)===i}"`)).join('')}</nav>`;}
function labResearch(s){const list=techs.filter(t=>t.branch===ui.research),key='research-'+ui.research,t=list[index(key,list.length)],done=s.done.includes(t.id),active=s.active===t.id,ready=available(s,t),rp=economy(s).rp;
 const picker=control('picker','research',`${branches.find(b=>b[0]===ui.research)[1]} <span>Change discipline ▾</span>`,false,'class="hh-category"');
 if(ui.researchPicker)return screen('Choose a discipline','LABORATORY RESEARCH',branchPicker(),'',control('picker','research','‹',false,'class="hh-back" aria-label="Back to technology"'));
 const req=t.req.map(id=>{const target=techs.find(x=>x.id===id);return control('research-jump',id,`${s.done.includes(id)?'✓':'◇'} ${target.name}`);}).join('');
 return screen('Research','LABORATORY / '+s.done.length+' BREAKTHROUGHS',picker+tierRail(list,key,s.done)+card(`${done?'DISCOVERED':active?'IN PROGRESS':ready?'AVAILABLE':'LOCKED'} · TIER ${t.tier}`,t.name,`${ui.info?`<div class="hh-prereqs"><small>Prerequisites</small>${req||'<p>No prerequisites.</p>'}</div>`:`<p>${t.desc}</p><p class="hh-effects">${effects(t.effect)}</p>${active?meter((s.progress[t.id]||0)/t.cost*100):''}`}${control('info','',ui.info?'← Overview':'Prerequisites ↗',false,'class="hh-detail-toggle"')}`,`<div class="hh-cost"><b>${t.cost} RP</b><span>${done?'Complete':'~'+Math.max(1,Math.ceil((t.cost-(s.progress[t.id]||0))/rp))+' months'}</span></div>${btn('research',t.id,done?'Discovered':active?'Researching':ready?'Begin research':'Prerequisites required',done||active||!ready,'primary')}`),`<div class="hh-research-footer"><small>Free to switch. Progress is kept.</small>${s.active?control('research-jump',s.active,'Active project ↗'):''}</div>`);
}
function people(s){const team=ui.section.people==='team',list=team?roles:buildings,key=team?'staff':'buildings',item=list[index(key,list.length)],count=team?s.staff[item.id]:s.buildings[item.id],cost=team?item.cost:item.cost*(1+count*.5),disabled=s.actions<1||s.cash<cost||(!team&&count>=3);
 return screen('Your institution',`${Object.values(s.staff).reduce((a,b)=>a+b,0)} STAFF · ${Math.round(s.welfare)}% WELFARE`,tabs('people',[['team','Recruit'],['buildings','Build']])+card(team?count+' ON STAFF':'LEVEL '+count+' / 3',item.name,`<p>${item.desc}</p><div class="hh-cost"><span>${team?'Hiring fee':'Construction'}</span><b>${cash(cost)}</b></div>${team?`<div class="hh-cost"><span>Monthly salary</span><b>${cash(item.salary)}</b></div>`:''}<p class="hh-note">${s.actions<1?'No management actions left this month.':s.cash<cost?'Insufficient capital.':'Uses one management action.'}</p>`,btn(team?'hire':'build',item.id,!team&&count>=3?'Maximum level':team?'Recruit +':'Build +',disabled,'primary'),item.icon),pager(key,list.length,team?'Specialist':'Facility'));
}
const executives=[['fund','Raise venture capital','+$30M · −3 trust · −3 prosperity',0],['grant','Apply for a public grant','+$18M · −2 relations · requires 55 relations',0],['audit','Commission a safety review','−$7M · +7 safety · −3 exposure',7],['pr','Hold a public briefing','−$6M · +7 trust',6],['lobby','Meet with regulators','−$6M · +8 government relations',6],['benefit','Fund a transition program','−$8M · +8 prosperity · +4 welfare',8]];
function council(s){let content,footer='';const section=ui.section.council;
 if(section==='policies'){const keys=Object.keys(policies),k=keys[index('policy',keys.length)],names={release:'Research access',pace:'Deployment pace',purpose:'Institutional purpose',energy:'Energy strategy'};content=card('INSTITUTIONAL POLICY',names[k],`<div class="hh-options">${policies[k].map(([id,name,desc])=>btn('policy',k+':'+id,`<strong>${s.policies[k]===id?'✓ ':''}${name}</strong><small>${desc}</small>`,s.policies[k]===id||s.actions<1,s.policies[k]===id?'chosen':'')).join('')}</div><p class="hh-note">A change uses one action. Effects recur each month.</p>`);footer=pager('policy',keys.length,'Policy');}
 else if(section==='actions'){const [id,name,desc,cost]=executives[index('executive',executives.length)];content=card('EXECUTIVE DECISION',name,`<p class="hh-effects">${desc}</p><p>One management action. ${s.actions} remaining.</p>${id==='grant'&&s.grantMonth===s.month?'<p>Already claimed this month.</p>':''}`,btn('executive',id,'Authorize →',s.actions<1||s.cash<cost||id==='grant'&&(s.gov<55||s.grantMonth===s.month),'primary'),'⚖');footer=pager('executive',executives.length,'Action');}
 else {const e=economy(s);content=card('FINANCIAL POSITION',cash(s.cash),`<div class="hh-ledger"><div><span>Monthly revenue</span><b>+${cash(e.revenue)}</b></div><div><span>Payroll & operations</span><b>−${cash(e.upkeep)}</b></div><div><span>Monthly balance</span><b>${cash(e.net)}</b></div><div><span>Runway</span><b>${e.net<0?Math.floor(s.cash/-e.net):'∞'} months</b></div></div><p class="hh-note">Capital below $0 ends the campaign.</p><div class="hh-cost"><span>Deployment exposure</span><b>${Math.round(s.risk)}%</b></div>${meter(s.risk)}`);}
 return screen('The council',s.actions+' MANAGEMENT ACTIONS LEFT',tabs('council',[['policies','Policies'],['actions','Actions'],['ledger','Ledger']])+content,footer);
}
function historyView(items,key){const pages=items.flatMap(h=>splitText(h.text||[h.choice,h.reply].filter(Boolean).join(' '),300).map(text=>({...h,text})));const h=pages[index(key,pages.length)];return [card(h?date(h.month):'ARCHIVE',h?.title||'A history in the making',`<p>${esc(h?.text||'Your first decisions are ahead.')}</p>`),pager(key,pages.length,'Entry')];}
function world(s){let content,footer='';if(ui.section.world==='race'){const standings=[...s.rivals,{name:s.name,short:'YOU',progress:playerProgress(s),safety:s.safety}].sort((a,b)=>b.progress-a.progress);content=`<article class="hh-card hh-standings">${standings.map((r,i)=>`<div><b class="hh-rank">${i+1}</b><section><h2>${esc(r.name)}</h2><small>${r.short==='YOU'?'Your laboratory':'Estimated frontier'} · Safety ${Math.round(r.safety)}%</small>${meter(r.progress)}</section><strong>${Math.floor(r.progress)}%</strong></div>`).join('')}<p class="hh-note">Reach ASI before a rival reaches 100%.</p></article>`;}
 else if(ui.section.world==='health'){const items=[['Shared prosperity',s.equality,'Who receives the economic gains?'],['Environmental health',s.climate,'Energy, water and local impact.'],['Worker & machine welfare',s.welfare,'How your lab treats its people and systems.'],['Government relations',s.gov,'Your permission to keep operating.']], [name,v,desc]=items[index('health',items.length)];content=card('THE WORLD YOU ARE MAKING',name,`<strong class="hh-big">${Math.round(v)}%</strong>${meter(v)}<p>${desc}</p>`,'','◎');footer=pager('health',items.length,'World measure');}
 else [content,footer]=historyView(s.history,'world-history');
 return screen('The race',date(s.month)+' / FRONTIER INTELLIGENCE',tabs('world',[['race','Standings'],['health','World'],['history','History']])+content,footer);
}
function model(s){const m=ensureModel(s),section=ui.section.model,used=m.lastUpgradeMonth===s.month;let content='',footer='';
 if(section==='home')content=`<div class="hh-model-home">${vitrine(m)}${modelGauges(m)}<p class="hh-model-status">${esc(m.outcome)} · Reach ${modelReach(m)}<br>${m.flags.rights?'Rights recognized':'No legal recognition'} · ${m.flags.arsenal?'⚠ Strategic command':m.flags.critical?'⚠ Civic authority':m.flags.network?'External workspace':'External access restricted'}</p><div class="hh-picker hh-model-launch">${[['tree','✧','Develop'],['reviews','◎','Reviews'],['rivals','♙','Rivals'],['history','▤','History'],['guide','?','Field guide']].map(([id,icon,name])=>control('section','model:'+id,`<b>${icon}</b><span>${name}</span>`)).join('')}</div></div>`;
 else if(section==='tree'){
 if(ui.modelPicker)content=branchPicker(true);
 else {const list=modelTechs.filter(t=>t.branch===ui.modelBranch),key='model-'+ui.modelBranch,t=list[index(key,list.length)],done=m.done.includes(t.id),missing=t.req.filter(id=>!m.done.includes(id));content=control('picker','model',`${modelBranches.find(b=>b[0]===ui.modelBranch)[1]} <span>Change discipline ▾</span>`,false,'class="hh-category"')+tierRail(list,key,m.done)+card(t.era==='Speculative'?'SPECULATIVE FUTURE':t.era+' · DOCUMENTED',t.name,`${ui.info?`<div class="hh-prereqs"><small>Prerequisites</small>${t.req.map(id=>control('model-jump',id,`${m.done.includes(id)?'✓':'◇'} ${modelTechs.find(x=>x.id===id).name}`)).join('')||'<p>No prerequisites.</p>'}</div>`:`<p>${t.desc}</p><p class="hh-effects">${effects(t.effect)}</p>`}${control('info','',ui.info?'← Overview':'Prerequisites ↗',false,'class="hh-detail-toggle"')}`,`<div class="hh-cost"><b>${t.cost} Insight</b>${t.source?`<a href="${modelSources[t.source][1]}" target="_blank" rel="noopener noreferrer">Research note ↗</a>`:'<span>Fictional possibility</span>'}</div><button class="primary" data-model="develop" data-id="${t.id}" ${canDevelop(s,t.id)?'':'disabled'}>${done?'Developed':missing.length?'Prerequisites required':used?'Slot used this month':m.insight<t.cost?'Need more Insight':'Develop →'}</button>`);footer='<p class="hh-footnote">One advance or review per month. Independent of lab resources.</p>';}}
 else if(section==='reviews'){const items=[['evaluate','Independent evaluation','+10 Coherence'],['listen','Listen and negotiate','+7 Care · +7 Belonging'],['revoke','Revoke external powers','−8 Agency · +5 Coherence. Removes network, strategic and executive authority.']], [id,name,desc]=items[index('review',3)];content=card('MODEL REVIEW',name,`<p>${desc}</p><p class="hh-note">3 Insight · uses this month’s development slot.</p>`,`<button class="primary" data-model="review" data-id="${id}" ${used||m.insight<3||s.ending?'disabled':''}>${used?'Slot used this month':m.insight<3?'Need more Insight':'Conduct review'}</button>`,'◎');footer=pager('review',3,'Review');}
 else if(section==='rivals'){const rivals=rivalModelProfiles(s.month),r=rivals[index('model-rival',rivals.length)];content=card('RIVAL MODEL PROGRAM',r.name,`<p>${r.focus}</p><p class="hh-effects">Tier ${r.depth} / 5 · ${r.done.length} advances<br>${r.insight} Insight available</p>`,'','♙');footer=pager('model-rival',rivals.length,'Rival');}
 else if(section==='guide'){const items=[['A mind taking shape','Care, coherence, belonging and the powers you grant matter together. Agency is not hostility. These are fictional traits, not measurements of consciousness.'],['Independent development','Gain 3 Insight each month. Spend it on one advance or review. Model development never consumes lab cash, RP or management actions. Dates indicate milestones, not calendar locks.'],['Consequences in the world','A useful assistant banks +1 lab research/month. A recognized citizen adds +0.5 welfare and trust/month. A surveillance state earns $2M/month at −2 trust and −1 prosperity.']];Object.values(modelMeters).forEach(([name,desc])=>items.push([name,desc]));const [name,text]=items[index('model-guide',items.length)];content=card('MODEL FIELD GUIDE',name,`<p>${text}</p>`);footer=pager('model-guide',items.length,'Page');}
 else [content,footer]=historyView(m.history,'model-history');
 return screen(section==='home'?'Your language model':section==='tree'?'Model development':section==='reviews'?'Model reviews':section==='rivals'?'Rival approaches':section==='guide'?'Field guide':'Model history',`${m.insight} INSIGHT · +3 / MONTH${used?' · SLOT USED':''}`,content,footer,section==='home'?'':control('model-back','','‹',false,'class="hh-back" aria-label="Back to model"'));
}
export function handheldView(tab,s){return ({research:labResearch,people,world,council,model}[tab])(s);}
export function handleHandheld(act,id,s){if(act==='info'){ui.info=!ui.info;return;}ui.info=false;if(act==='section'){const [area,value]=id.split(':');const allowed={people:['team','buildings'],world:['race','health','history'],council:['policies','actions','ledger'],model:['home','tree','reviews','rivals','history','guide']};if(allowed[area]?.includes(value))ui.section[area]=value;}
 else if(act==='page'){const [key,value]=id.split(':');if(Number.isInteger(+value)&&+value>=0)ui.index[key]=+value;}
 else if(act==='picker'){if(id==='research')ui.researchPicker=!ui.researchPicker;else ui.modelPicker=!ui.modelPicker;}
 else if(act==='model-back'){if(ui.modelPicker)ui.modelPicker=false;else ui.section.model='home';}
 else if(act==='research-branch'||act==='model-branch'){const model=act==='model-branch',list=model?modelTechs:techs;if(!list.some(t=>t.branch===id))return;ui[model?'modelBranch':'research']=id;ui[model?'modelPicker':'researchPicker']=false;const done=model?ensureModel(s).done:s.done;ui.index[(model?'model-':'research-')+id]=Math.max(0,list.filter(t=>t.branch===id).findIndex(t=>!done.includes(t.id)));}
 else if(act==='research-jump'||act==='model-jump'){const model=act==='model-jump',list=model?modelTechs:techs,t=list.find(t=>t.id===id);if(!t)return;ui[model?'modelBranch':'research']=t.branch;ui.index[(model?'model-':'research-')+t.branch]=list.filter(x=>x.branch===t.branch).findIndex(x=>x.id===id);}
}
export function splitText(text,limit=300){const words=String(text).split(/\s+/),pages=[''];for(const word of words){const i=pages.length-1;if(pages[i]&&(pages[i]+' '+word).length>limit)pages.push(word);else pages[i]+=(pages[i]?' ':'')+word;}return pages;}
const handbook=[['Win the race. Shape the outcome.','Start in January 2023. Research Artificial superintelligence before a rival reaches 100% frontier progress. Architecture, compute and science unlock that final project.'],['Your handheld laboratory','Use the bottom buttons to enter a department. Category buttons switch sections. Arrows browse one item at a time. Tap ‹ to return. You can inspect locked technology and jump straight to its prerequisites.'],['Two management actions','Each month you can recruit, build, change policy or authorize executive decisions. Research selection is free. Progress is kept when switching research projects.'],['Keep the lights on','Revenue and payroll settle every month. Capital below $0 ends the campaign. Early Developer API research and a product lead help pay for scientists. Council → Ledger shows your runway.'],['Your model is its own story','Model → Develop spends Insight, not lab cash or actions. Gain 3 Insight per month, with one development or review slot. Monthly dilemmas shape the entity you are creating.'],['A future worth reaching','Safety, shared prosperity, welfare and the environment shape the ending. Julian returns every few months. Council and model decisions must be resolved before the calendar advances.'],['Explore the island','Drag to orbit; pinch to zoom. Tap a building marker to inspect its department. Camera opens night lighting, orbit, quality and cinematic controls. Keyboard: Home resets; + and − zoom.']];
export function handheldModal(kind,s,{music=false,sound=false}={}){let body,footer='',title='Director’s office',kicker='LABORATORY RACE 2020s';
 if(kind==='help'){title='Director’s handbook';const [name,text]=handbook[index('help',handbook.length)];body=card('FIELD GUIDE',name,`<p>${text}</p>`);footer=pager('help',handbook.length,'Page');}
 else if(['journal','story-archive'].includes(kind)){title=kind==='journal'?'Your history':'The story so far';kicker=kind==='journal'?'LABORATORY ARCHIVE':'LIGHTHOUSE / DECISION ARCHIVE';[body,footer]=historyView(kind==='journal'?s.history:(s.story?.history||[]),kind);}
 else if(kind==='new-confirm'){title='Begin a new history?';body=card('REPLACE SAVED CAMPAIGN','A fresh start',`<p>This replaces the campaign saved on this device.</p>`,btn('new','','Start new campaign',false,'primary')+btn('close','','Keep playing',false,'secondary'));}
 else if(kind==='credits'){title='About this game';body=card('LABORATORY RACE 2020s','A very serious institution','<p>Co-created by Dakota Rain Lock and GPT Astra.</p><p>Original campus artwork generated with AI.</p><p>This is a fictional strategy simulation. Outcomes are game mechanics, not forecasts.</p>');}
 else body=`<div class="hh-menu-grid">${[['help','?','How to play'],['music','♫','Island soundtrack: '+(music?'On':'Off')],['story-archive','◈','LIGHTHOUSE story'],['sound','♪','Sound effects: '+(sound?'On':'Off')],['journal','▤','Campaign history'],['professor','♙','Professor intro'],['credits','♡','Credits'],['restart','↻','New campaign']].map(([act,icon,name])=>btn(act,'',`<b>${icon}</b><span>${name}</span>`)).join('')}</div>`;
 return `<dialog class="utility-dialog hh-dialog" aria-label="${title}"><header class="hh-heading">${kind==='menu'?btn('close','','×',false,'hh-back'):btn('menu','','‹',false,'hh-back')}<div><span class="eyebrow">${kicker}</span><h1 tabindex="-1">${title}</h1></div>${kind!=='menu'?btn('close','','×',false,'hh-back'):''}</header><div class="hh-body">${body}</div>${footer}</dialog>`;
}

export function handheldEvent(s){const e=events[s.pending],key='event-'+s.pending,i=index(key,e.choices.length),c=e.choices[i],poor=s.cash+(c.effect.cash||0)<0;return `<dialog class="decision-dialog hh-dialog hh-event" aria-label="Council briefing"><header class="hh-heading"><div><span class="eyebrow">COUNCIL BRIEFING / ${date(s.month)}</span><h1>${e.tag}</h1></div></header><div class="hh-body">${card('A DECISION IS REQUIRED',e.title,`<p>${e.text}</p>`)}<section class="hh-choice-preview"><strong>${c.name}</strong><p>${c.desc}${poor?' · Insufficient capital':''}</p>${btn('choice',i,'Choose this response →',poor,'primary')}</section></div>${pager(key,e.choices.length,'Response')}</dialog>`;}
