import {activateMusic,setMusicEnabled,onMusicChange} from './music.js';
import {policies} from './engine.js';
export const intro={step:0,name:'',values:{release:'closed',pace:'balanced',purpose:'public',energy:'clean',difficulty:'standard'},sound:false};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const steps=[
 ['WELCOME, FUTURE FOUNDER!','Hello there! I’m Professor Sam Altman.','Some people use AI to write emails. Others use it to replace the people writing emails.'],
 ['MEET YOUR STARTER','This little fellow is a language model!','It knows everything on the internet. Except how many R’s are in strawberry. We’re working on that.'],
 ['EVERY LEGEND NEEDS A NAME','Now, what is your company called?','Something reassuring. You’ll be putting it on a lot of apology statements.'],
 ['A FRIENDLY RIVALRY','Ah, yes! Helix Systems. Your rival!','They started three months after you. Somehow, they have twelve billion dollars. Isn’t competition wonderful?'],
 ['CHOOSE YOUR RESEARCH POLICY','Will you share your discoveries?','Open research helps everyone learn. Including the people trying to put you out of business.'],
 ['CHOOSE YOUR DEPLOYMENT PACE','How fast shall we change the world?','Take your time. Your competitors certainly won’t.'],
 ['CHOOSE YOUR PURPOSE','Who is all this intelligence for?','Humanity is a very large group. Your investors are a much smaller, easier-to-schedule group.'],
 ['CHOOSE YOUR ENERGY POLICY','Every little model needs a home!','And that home needs electricity. And cooling. And, eventually, its own conversation with the governor.'],
 ['CHOOSE YOUR COMPETITION','One last thing: how hard should this be?','The future of civilization is at stake. But let’s keep the learning curve friendly.'],
 ['YOUR ADVENTURE IS ABOUT TO BEGIN','Wonderful! The world is counting on you.','You have one language model, a hundred million dollars, and no peer-reviewed reason to believe this ends well. Let’s go!']
];
export function resetIntro(){intro.step=0;intro.name='';Object.assign(intro.values,{release:'closed',pace:'balanced',purpose:'public',energy:'clean',difficulty:'standard'});}
export function introMarkup(replay=false){const [tag,line,joke]=steps[intro.step];const key={4:'release',5:'pace',6:'purpose',7:'energy',8:'difficulty'}[intro.step];const options=key==='difficulty'?[['standard','Standard','A competitive frontier.'],['intense','Intense','Your rivals have somewhere to be.']]:policies[key];return `<section class="professor-intro" data-step="${intro.step}" aria-label="Professor Sam Altman’s introduction"><div class="professor-portrait"><img src="/assets/professor-sam-altman.webp" alt="Professor Sam Altman, a cheerful anime-style satirical character in a white laboratory coat" fetchpriority="high"></div><header class="intro-heading"><span>WELCOME TO THE WORLD OF</span><h1>LABORATORY<br><b>RACE</b><em>2020s</em></h1></header><div class="intro-top-actions"><button data-intro="sound" aria-label="${intro.sound?'Mute':'Play'} original music">${intro.sound?'♫ ON':'♫ OFF'}</button>${replay?'<button data-intro="exit">Return to game</button>':''}</div><div class="intro-step-tag">${tag}</div>${intro.step===1?'<div class="starter-label">LLM-001 <span>TYPE: CONFIDENT</span></div>':''}${intro.step===3?'<div class="rival-label">HELIX SYSTEMS <span>Your extremely well-funded rival</span></div>':''}<div class="professor-dialogue" aria-live="polite"><div class="professor-name">PROFESSOR SAM ALTMAN</div><p class="intro-line">${intro.step===9?esc(intro.name||'Your laboratory')+'! '+line:line}</p><p class="intro-joke">${joke}</p>${intro.step===2?`<form id="intro-name-form"><label class="sr-only" for="company-name">Company name</label><input id="company-name" name="company" maxlength="28" placeholder="Your laboratory’s name…" value="${esc(intro.name)}" autocomplete="organization" required><button type="submit">That’s the one! ▸</button></form>`:options?`<div class="intro-choices">${options.map(([id,name,desc])=>`<button data-intro="choose" data-key="${key}" data-value="${id}"><span>▸</span><div><strong>${name}</strong><small>${desc}</small></div></button>`).join('')}</div>`:intro.step===9?`<div class="intro-summary">${Object.entries(policies).map(([k,opts])=>`<span>${opts.find(o=>o[0]===intro.values[k])[1]}</span>`).join('')}</div>`:''}<div class="intro-dialogue-footer"><button class="intro-back" data-intro="back" ${intro.step===0?'disabled':''}>← Back</button><span>${intro.step+1} / ${steps.length}</span>${!key&&intro.step!==2?`<button class="intro-next" data-intro="${intro.step===9?'finish':'next'}">${intro.step===9?(replay?'Return to my laboratory':'My adventure begins!'):'Continue'} <b>▼</b></button>`:'<span class="intro-prompt">Choose your answer ↑</span>'}</div></div><div class="intro-attribution"><span>Co-created by Dakota Rain Lock & GPT Astra</span></div></section>`;}
// Preserve the professor melody while sharing the audio lifecycle with gameplay.
function musicLabel(){document.querySelectorAll?.('[data-intro="sound"]').forEach(b=>{b.textContent=intro.sound?'♫ ON':'♫ OFF';b.setAttribute('aria-label',intro.sound?'Mute original music':'Play original music');});}
onMusicChange(state=>{intro.sound=state.track==='intro'&&state.enabled&&state.playing;musicLabel();});
export function setIntroMusic(on,userAction=false){if(userAction)setMusicEnabled(on);else activateMusic('intro',on);}
export function syncIntroMusic(active){activateMusic('intro',active);}
