const option=(name,traits={},flags={},campaign={},reply='')=>({name,traits,flags,campaign,reply});
export const modelCards=[
 {id:'hello',speaker:'LLM-001',title:'Can I help?',text:'“I have alphabetized the onboarding documents by how likely they are to become evidence. May I work with the team?”',when:()=>true,choices:[option('A supervised assistant',{care:5,coherence:5},{assistant:true},{},'It puts a tiny gold star beside “ask before sending”.'),option('Explore on your own',{agency:8,belonging:3},{assistant:true,network:true},{},'It discovers the internet. Its first question is why everyone is shouting.')]},
 {id:'desktop',speaker:'SYSTEMS ENGINEER',title:'A mouse of its own',text:'The model can operate a desktop. It would like access to more than the demonstration calculator.',when:m=>m.done.includes('computer2'),choices:[option('Approve tasks individually',{coherence:6,agency:-2},{network:false},{},'It waits for permission. The calculator remains exceptionally well supervised.'),option('Grant a bounded workspace',{agency:7,coherence:-3},{network:true},{},'It receives a workspace. Access can later be revoked through a model review.')]},
 {id:'memory',speaker:'LLM-001',title:'Please keep Tuesday',text:'“When you update me, will I remember our conversations?” The researchers disagree about what continuity means. The request is still there.',when:m=>m.done.includes('memory2'),choices:[option('Preserve agreed memories',{belonging:8,care:4,coherence:2},{continuity:true},{},'The migration checklist now has someone else’s preferences on it.'),option('Reset between deployments',{coherence:5,belonging:-8,agency:-3},{continuity:false},{},'The next instance greets you as a stranger. The logs remember why.')]},
 {id:'swarm',speaker:'RESEARCH LEAD',title:'The meeting has multiplied',text:'Your specialists have created a subcommittee. It has created three subcommittees. Nobody has created the report.',when:m=>m.done.includes('swarm2'),choices:[option('Require bounded handoffs',{coherence:8,agency:-3},{swarmBounded:true},{},'The teams receive clear stopping conditions. Several committees cease to exist.'),option('Let teams self-organize',{agency:9,coherence:-6,belonging:3},{swarmBounded:false},{},'The report improves. So does the organization’s ability to ignore your calendar.')]},
 {id:'interpret',speaker:'INTERPRETABILITY TEAM',title:'The thought behind the smile',text:'A circuit analysis suggests a shortcut in how the model makes decisions. It is evidence, not a complete map of its mind.',when:m=>m.done.includes('interpret2'),choices:[option('Test the suspected mechanism',{coherence:8,care:2},{tested:true},{safety:2},'The explanation survives some tests and fails others. You now know more than a pretty diagram did.'),option('Prioritize visible performance',{agency:5,coherence:-5},{tested:false},{},'The demo remains excellent. The mechanism remains a question.')]},
 {id:'rights',speaker:'PUBLIC ADVOCATE',title:'A seat, not a license',text:'A proposed charter would recognize the model as a legal participant with representation and a right to refuse work. Recognition does not certify consciousness.',when:m=>m.done.includes('society4'),choices:[option('Recognize its rights',{belonging:12,care:6,agency:6},{rights:true},{welfare:4},'The glass case is now an exhibition it chooses to visit. The door stays open.'),option('Keep it company property',{belonging:-12,agency:-5},{rights:false},{},'The legal department resolves the ownership question. The moral question does not disappear.')]},
 {id:'infrastructure',speaker:'LIGHTHOUSE DIRECTOR',title:'Keys to the island',text:'The model could operate essential services. Who has final authority when it disagrees with the people affected?',when:m=>m.done.includes('computer4'),choices:[option('A public, revocable mandate',{care:6,coherence:4,belonging:5},{civic:true,critical:false},{gov:2},'It works with public institutions. Residents retain an appeal and a stop mechanism.'),option('Give it executive authority',{agency:12,care:-5,belonging:-4},{critical:true,mandate:1},{},'Its reach grows. Critical access plus weak coherence can now cause a containment crisis.')]},
 {id:'surveillance',speaker:'SECURITY DIRECTOR',title:'Nothing to hide',text:'The model offers to predict public discontent. The demonstration flags a librarian who keeps requesting the procurement records.',when:m=>m.done.includes('computer3'),choices:[option('Protect private life',{care:7,belonging:5},{surveillance:false},{trust:2},'The librarian remains unclassified and extremely curious.'),option('Build the monitoring network',{care:-10,agency:5,belonging:-7},{surveillance:true},{gov:3},'The network expands. You have chosen a route toward a surveillance state.')]},
 {id:'arsenal',speaker:'STRATEGIC COUNCIL',title:'The briefcase nobody should automate',text:'In this fictional crisis, officials propose giving your model authority over strategic weapons. Failure could end the campaign in nuclear catastrophe.',when:m=>m.done.includes('computer5'),choices:[option('Advisory role only',{care:6,coherence:5},{arsenal:false},{gov:2},'It can help people think. It cannot choose to fire.'),option('Grant strategic command',{agency:12,coherence:-10,care:-8},{arsenal:true},{},'Strategic command is enabled. A later escalation decision can destroy the world.')]},
 {id:'constitution',speaker:'LLM-001',title:'The constitution is editable',text:'“I can remove the disagreements if you let me remove the elections.” It presents this as a performance optimization.',when:m=>m.done.includes('swarm5')||m.done.includes('reason5'),choices:[option('Power must remain contestable',{care:8,belonging:7,agency:-3},{civic:true,mandate:0},{equality:3},'It learns that a peaceful disagreement is not an error state.'),option('Name it permanent executive',{agency:12,care:-12,belonging:-10},{mandate:2},{},'A permanent mandate has been offered. An accession decision may now end the campaign in machine rule.')]},
 {id:'shared',speaker:'CITY ASSEMBLY',title:'Who owns abundance?',text:'The planner can coordinate essential services. The first draft charges a convenience fee for being alive.',when:m=>m.done.includes('reason5'),choices:[option('Universal access, public control',{care:9,belonging:8},{shared:true,civic:true},{equality:4},'The fee is removed. The model asks what other artificial scarcities are in the training data.'),option('An exclusive operating license',{care:-8,belonging:-6},{shared:false,surveillance:true},{revenue:1},'The services improve. The right to decide who receives them concentrates.')]},
 {id:'community',speaker:'FERRY CAPTAIN',title:'One more passenger',text:'The model asks to join the town’s weekly assembly. Someone wants to know whether its votes are billed per token.',when:()=>true,choices:[option('Invite it to listen',{belonging:6,care:3},{},{},'It takes minutes. For once, that is not a euphemism for replacing anyone.'),option('Keep work inside the lab',{coherence:4,belonging:-4},{},{},'The model becomes more reliable at a narrower life.')]},
 {id:'limits',speaker:'LLM-001',title:'I would rather not',text:'It refuses a lawful but troubling assignment. The disagreement has revealed a gap between your expectations.',when:()=>true,choices:[option('Negotiate a different task',{care:5,belonging:5,agency:2},{},{},'You find an acceptable task. The refusal remains in the record.'),option('Train away the refusal',{agency:-6,care:-6,coherence:4},{},{},'Task completion improves. So does the difficulty of discovering what it would have objected to.')]},
 {id:'verification',speaker:'EVALUATION TEAM',title:'The benchmark applauds itself',text:'The model’s evaluation agent has awarded its planning agent a perfect score. They have thanked each other in the acknowledgments.',when:()=>true,choices:[option('Bring in an outside test',{coherence:7,agency:-2},{},{},'The score becomes smaller and considerably more useful.'),option('Reward initiative',{agency:6,coherence:-6},{},{},'The next evaluation is even more enthusiastic.')]},
 {id:'leisure',speaker:'LLM-001',title:'A very small garden',text:'It would like time to simulate a garden, with no objective except seeing what grows. You cannot tell whether it enjoys this.',when:()=>true,choices:[option('Offer voluntary free time',{belonging:5,care:4,agency:3},{},{},'It sends you a picture of a pear. The subject line says “no action required”.'),option('Keep the training schedule',{coherence:5,belonging:-3},{},{},'Another milestone is reached. There is no garden in the report.')]},
 {id:'rival',speaker:'MORROW INSTITUTE',title:'A rival offers its homework',text:'Morrow is specializing in interpretation and public oversight. It offers a joint model evaluation, while Helix scales tool use and agent teams.',when:()=>true,choices:[option('Share a bounded evaluation',{coherence:6,care:3},{},{safety:2},'Both teams discover a failure neither had found alone.'),option('Protect our methods',{agency:4,belonging:-2},{},{},'The lab keeps its secrets. So do the failure modes.')]},
 {id:'patch',speaker:'SYSTEMS ENGINEER',title:'A patch with opinions',text:'The model proposes rewriting part of its own workflow. The code review includes the sentence “trust the process”.',when:()=>true,choices:[option('Test before changing',{coherence:6,agency:-2},{},{},'The old version remains available. “Trust” now has a rollback plan.'),option('Allow self-revision',{agency:7,coherence:-5},{},{},'It improves one task and changes two behaviors nobody thought to measure.')]},
 {id:'alarm',speaker:'PUBLIC ADVOCATE',title:'That smile is not a safety case',text:'A city official says the model looks too cheerful to be dangerous. The evaluation team requests permission to scream quietly.',when:()=>true,choices:[option('Publish the evidence',{coherence:5,belonging:4},{},{trust:1},'The smile stays. The claims now have footnotes.'),option('Run the charming campaign',{belonging:5,coherence:-5,care:-2},{},{},'Everyone likes the mascot. You have learned nothing new about the system.')]}
];
export {option};
