import {modelMeters} from './model-tech.js';
import {modelExpression} from './model-system.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={cash:'$M capital',trust:'public trust',safety:'lab safety',gov:'relations',equality:'prosperity',welfare:'welfare',revenue:'$M monthly revenue'};
const fx=delta=>Object.entries(delta).map(([k,v])=>`${v>0?'+':''}${v} ${modelMeters[k]?.[0]||labels[k]||k}`).join(' · ');
export function modelGauges(m){return `<div class="model-gauges">${Object.entries(modelMeters).map(([key,[name,desc]])=>`<div class="${key!=='agency'&&m[key]<35?'model-meter-alert':''}" title="${desc}"><span>${name} <b>${Math.round(m[key])}</b></span><meter min="0" max="100" value="${m[key]}" aria-label="${name}: ${Math.round(m[key])}. ${desc}"></meter></div>`).join('')}</div>`;}
export const vitrine=m=>`<div class="model-vitrine" data-model-vitrine><span>Preparing LLM-001…</span></div><div class="model-specimen-tag"><b>LLM-001</b><span>${esc(m.outcome)} · ${modelExpression(m)}</span></div>`;
export function modelDecisionView(s){const m=s.model,p=m.pending,r=m.receipt;return `<dialog class="model-dialog" aria-labelledby="model-decision-title"><div class="model-dialog-top"><span>THE MODEL / ${r?'AFTERMATH':'MONTH '+s.month}</span><button data-act="music" aria-label="Toggle gameplay music">♫</button></div>${vitrine(m)}${modelGauges(m)}<section class="model-choice-card" ${p?'data-model-swipe tabindex="0" aria-label="Decision card. Swipe horizontally or use the two choice buttons."':''}><div class="eyebrow">${r?'LLM-001':p.speaker}</div><h2 id="model-decision-title">${esc(r?.title||p.title)}</h2><p>${esc(r?.text||p.text)}</p>${p?`<div class="model-swipe-hint">← ${p.choices[0].name} <span>${p.choices[1].name} →</span></div>`:''}</section>${p?`<div class="model-decision-buttons">${p.choices.map((c,i)=>`<button data-model="choice" data-id="${i}" ${s.cash+(c.campaign.cash||0)<0?'disabled':''}><strong>${i?'':'← '}${esc(c.name)}${i?' →':''}</strong><small>${fx(c.traits)||'No immediate trait change'}</small>${Object.keys(c.campaign).length?`<small>Lab: ${fx(c.campaign)}</small>`:''}${c.ending?'<b class="model-final-warning">ENDS THIS CAMPAIGN</b>':''}${s.cash+(c.campaign.cash||0)<0?'<small>Insufficient capital</small>':''}</button>`).join('')}</div><p class="model-card-foot">Tap either choice or swipe the card. No management action cost.</p>`:'<button class="model-continue" data-model="dismiss">Continue →</button>'}</dialog>`;}
// Horizontal intentional gestures only. Vertical scrolling and cancellation never decide.
export function bindModelSwipes(root,onChoice){let drag=null;
 root.addEventListener('pointerdown',e=>{const card=e.target.closest?.('[data-model-swipe]');if(!card||e.button>0||e.isPrimary===false)return;card.setPointerCapture?.(e.pointerId);drag={card,x:e.clientX,y:e.clientY,id:e.pointerId};});
 root.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dy)>24&&Math.abs(dy)>Math.abs(dx)){drag.card.style.transform='';drag=null;return;}if(Math.abs(dx)>12)drag.card.style.transform=`translateX(${Math.max(-90,Math.min(90,dx))}px) rotate(${Math.max(-8,Math.min(8,dx/14))}deg)`;});
 const reset=()=>{if(drag)drag.card.style.transform='';drag=null;};
 root.addEventListener('pointercancel',reset);
 root.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;reset();if(Math.abs(dx)>80&&Math.abs(dx)>Math.abs(dy)*1.5)onChoice(dx>0?1:0);});
 root.addEventListener('keydown',e=>{if(!e.target.matches?.('[data-model-swipe]'))return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();onChoice(e.key==='ArrowRight'?1:0);}});
}
